<a href="https://colab.research.google.com/github/Yaninns/data_viz/blob/main/More%20advancted%20data%20structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dictionary

สามารถ index ด้วยอะไรก็ได้แต่ลำดับจะหายไป

In [3]:
ex_dict = {'a':10, '1':1, 'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [4]:
ex_dict['stat']

5

In [8]:
ex2_dict = {1:'one', 2:'two', 3:'three'}

In [9]:
ex2_dict[2]

'two'

#### การเพิ่มสมาชิก

In [10]:
ex2_dict[0] = 'zero'

In [11]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

#### คำสั่ง

In [13]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [14]:
for index in ex2_dict.keys():
  print(index)

1
2
3
0


In [15]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [17]:
for values in ex2_dict.values():
  print(values)

one
two
three
zero


dict เอาไปใช้ร่วมกับ Dataframe ของ pandas

numpy คือ package ที่ทำงานเกี่ยวกับ array ของตัวเลข (ที่มีคนเขียนขึ้นมาและนิยมใช้)
numpy -> number python

In [18]:
import numpy #เรียกใช้งาน package

สร้าง number array

In [24]:
ex2_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex2_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


การชี้ค่าใน numpy array

In [ ]:
ex_2d_array[1,2]

In [31]:
list_x = [[5.2,3.2,4.5],[9.1,0.1,0.3]] #การชี้ list
print(len(list_x)) #ดูว่ามีสมาชิกกี่ตัว
print(list_x[1])
print(list_x[1][2]) 

2
[9.1, 0.1, 0.3]
0.3


Operations

In [48]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex2_2d_array)

NameError: ignored

In [42]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

NameError: ignored

In [ ]:
ex_2d_array + ex2_2d_array

In [41]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [47]:
ex_2d_array - ex2_2d_array

NameError: ignored

matrix multiplication (dot product)

In [45]:
ex2_2d_array * ex2_2d_array #การคูณแบบ array คือเอาตำแหน่งเดียวกันมาคูณกัน ต่างจาก การคูณ matrix

array([[1, 0, 0],
       [0, 0, 1]])

In [ ]:
numpy.dot(ex2_2d_array, ex2_2d_array)

In [ ]:
print(ex_2d_array)
print(ex_2d_array.T) #การทรานสโพส matrix

## matrix slicing

HW 5 เขียน function คูณ matrix
แล้ว test กับ matrix
(2,3)*(3,2)
(4,4)*(4,1)
(2,2)*(2,2)